server:
  host: 0.0.0.0
  port: 4097
  base_path: /tejo9855/agency
  workers: 2
  timeout: 120

server_name: potato annotator
annotation_task_name: Agency Annotation

task_dir: .

data_files:
  - data/dolma_combined_final_sample_with_llm_summary_safeid_with_spans.csv
output_annotation_dir: annotation_output/results/
output_annotation_format: json
annotation_codebook_url: ""

item_properties:
  id_key: safe_instance_id
  text_key: sampled_text
  kwargs:
    - source
    - llm_summary

user_config:
  allow_all_users: true
  users: []

list_as_text:
  text_list_prefix_type: none
  horizontal: true

alert_time_each_instance: 100000

annotation_schemes:
  - annotation_type: likert
    name: agency_focalization
    description: "Is the text focused on the lived experiences of a specific character(s)?"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_emotion
    description: "Does the text include explicit emotional details of a specific character(s)? (He felt sad, she likes, etc.)"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_cognition
    description: "Does the text include explicit cognitive details of a specific character(s)? (I think, she believes, etc.)"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_motivation
    description: "Does the text include explicit motivational details of a specific character(s)? (I want, she desires, etc.)"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_direct_speech
    description: "Does the text include explicit direct speech details of a specific character(s)? (Direct quotes, \"I like this new iPhone.\")"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_indirect_speech
    description: "Does the text include explicit indirect speech details of a specific character(s)? (He said, she told me, etc.)"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_message_exchange
    description: "Does the text seem to be from some kind of message board or forum? (Reddit posts, comments, FAQ forums, etc.)"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_change_of_state
    description: "Does the text include explicit change of state details of a specific character(s)? (He got sad, she won the lottery, etc.)"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

  - annotation_type: likert
    name: agency_conflict
    description: "Does the text include explicit conflict details of a specific character(s)? (He argued, the storm destroyed the house, the computer is broken, etc.)"
    size: 5
    min_label: "Strongly Disagree"
    max_label: "Strongly Agree"
    label_requirement:
      required: false

ui:
  show_progress: true
  show_instructions: true
  allow_navigation: true
  allow_editing: true

instance_display:
  resizable: false
  fields:
    - key: source
      type: text
    - key: llm_summary
      type: text
    - key: sampled_text
      type: text

task_layout: layouts/task_layout_custom.html
site_dir: default
